# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HymnDBFinal' do
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'MaterialComponents'
    pod 'PDFReader'
    pod 'IBAnimatable'
    pod 'IoniconsKit'
    # pod 'AudioKit', '~> 4.0'

    use_frameworks!


    target 'HymnDBFinalTests' do
      inherit! :search_paths
      end

    target 'HymnDBFinalUITests' do
      inherit! :search_paths
    end
end
