# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'HymnDBFinal' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Alamofire', '~> 4.7'
  pod 'MaterialComponents'
  pod 'PDFReader'
  use_frameworks!

  # Pods for HymnDBFinal

end
